### ISSUE TITLE
npm install reselect and create queries folder

### ISSUE THREAD

**Issue by banderson** [banderson/generator-redux#4]

**Comment by SpencerCDixon** [comment]
Do you want reselect to be included in the generator?  I've been putting my selectors in a 'selectors' folder do you use 'queries' or am I misunderstanding?

I'm pretty new to JS community/react/redux but I'm super down to try and help out and add to this generator if you'd like.  You're talk at e4e was super useful for me!  Just got functional js in the mail today :)

**Comment by banderson** [comment]
Hey Spencer!

Indeed, I always use reselect. And the terms `query` and `selector` are synonymous to me, for whatever reason I just feel like `queries` resonates more with those new to the terminology and stack. I've been flip-flopping on what to call them here though :/ I may just revert to `selectors/` if that's the more common use

Good to meet you the other day, thanks for following up!

**Comment by SpencerCDixon** [comment]
Sweet!  Figured they were probably synonyms.  When I get some free time I'll see if I can figure out how to add it to the generator.  Never used Yeo before so should be a good learning exercise

**Comment by banderson** [comment]
If you want to hints to get started, I'd be glad to help. I'll try to type something quick up in the next few days, would be great to have that in here.
